---
- name: Pull web Docker image from Docker Hub
  docker_image:
    name: yapadinithi/buzbud-web-action
    tag: "{{ web_image_tag }}"
    source: pull

- name: Run web container
  docker_container:
    name: web-container
    image: "yapadinithi/buzbud-web-action:{{ web_image_tag }}"
    state: started
    restart_policy: always
    ports:
      - "80:80"

- name: Pull API Docker image from Docker Hub
  docker_image:
    name: yapadinithi/buzbud-api-action
    tag: "{{ api_image_tag }}"
    source: pull

- name: Run API container
  docker_container:
    name: api-container
    image: "yapadinithi/buzbud-api-action:{{ api_image_tag }}"
    state: started
    restart_policy: always
    ports:
      - "8080:8080"
      
