name: Build, Push Docker Images, and Update Linode Server

on:
  push:
    branches:
      - '**'  # Trigger the workflow on pushes to any branch

jobs:
  build-web:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Set up Docker Compose
      - name: Set up Docker Compose
        uses: docker/setup-buildx-action@v2

      # Step 4: Build and Push the Web Image using Docker Compose
      - name: Build and push web service using Docker Compose
        run: |
          docker-compose -f docker-compose.yml build web  # Build only the web service
          docker-compose -f docker-compose.yml push web  # Push the web service image
        env:
          DOCKER_CLI_EXPERIMENTAL: enabled

  build-api:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Set up Docker Compose
      - name: Set up Docker Compose
        uses: docker/setup-buildx-action@v2

      # Step 4: Build and Push the API Image using Docker Compose
      - name: Build and push API service using Docker Compose
        run: |
          docker-compose -f docker-compose.yml build api  # Build only the API service
          docker-compose -f docker-compose.yml push api  # Push the API service image
        env:
          DOCKER_CLI_EXPERIMENTAL: enabled

  update-linode:
    name: Update Linode Server
    needs:
      - build-web
      - build-api  # This job will wait for both build-web and build-api jobs to finish
    runs-on: ubuntu-latest
    steps:
      # Step 1: Execute remote SSH commands
      - name: Execute remote SSH commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            # Navigate to the deployment directory and pull the latest images
            cd /path/to/your/deployment
            docker-compose pull  # Pull the latest images from Docker Hub
            docker-compose up -d  # Restart the services with the new images
